// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using QuilvianSystemBackend.Repositories;

#nullable disable

namespace QuilvianSystemBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910031500_RenameTrxPatientEncounterAndPrescriptionToCanonicalPrefix")]
    partial class RenameTrxPatientEncounterAndPrescriptionToCanonicalPrefix
    {
    }
}