// <auto-generated />
//
// Dihasilkan oleh tooling\migrations\Update-MigrationHistory.ps1. Jangan disunting manual.
//
// Berkas ini memuat atribut [DbContext] dan [Migration] milik migration yang berkas
// Designer-nya diarsipkan ke Migrations\History\ dan tidak ikut dikompilasi.
//
// Atribut inilah yang dipakai EF Core untuk mengenali sebuah migration. Tanpa berkas
// ini, migration di bawah menjadi TIDAK TERLIHAT oleh EF: "migrations list" hanya
// melihat sebagian, "database update" tidak menerapkan apa pun namun tetap menjawab
// "Done.", dan "migrations add" menghasilkan migration berisi seluruh skema dari nol.
//
// Yang TIDAK dibawa ke sini adalah BuildTargetModel. Method itulah sumber beban
// kompilasinya, dan hanya dibutuhkan oleh migration bermuatan data serta oleh
// "migrations remove" pada migration terbaru; keduanya tetap dikompilasi utuh.
//
// Untuk mengompilasi kembali seluruh Designer:
//     dotnet build -p:FullMigrationMetadata=true

using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using QuilvianSystemBackend.Repositories;

#nullable disable

namespace QuilvianSystemBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516060830_initializeSetup")]
    partial class initializeSetup
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519172427_initializeEmployeeClean")]
    partial class initializeEmployeeClean
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519184429_changeEmpAttendanceAddWorkSchedule")]
    partial class changeEmpAttendanceAddWorkSchedule
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521073448_adjustmentUserEmployeeDoctorExternal")]
    partial class adjustmentUserEmployeeDoctorExternal
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521081743_initializeLeaveBalanceAndLeaveRequest")]
    partial class initializeLeaveBalanceAndLeaveRequest
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521090146_initializeOvertimeReq")]
    partial class initializeOvertimeReq
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521093156_changeStruktureCredentialLicense")]
    partial class changeStruktureCredentialLicense
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521182154_AddWorkforceClinicalPrivilege")]
    partial class AddWorkforceClinicalPrivilege
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521184038_AddWorkforceHealthRecord")]
    partial class AddWorkforceHealthRecord
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523164636_InitializeWfpOnBoardingOffBoardingContractHistory")]
    partial class InitializeWfpOnBoardingOffBoardingContractHistory
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523171252_AddWfpCompetencySkillMatrix")]
    partial class AddWfpCompetencySkillMatrix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523173936_AddPerformanceReview")]
    partial class AddPerformanceReview
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523175431_AddWfpDisciplinaryAction")]
    partial class AddWfpDisciplinaryAction
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523180640_AddWfpComplianceAlert")]
    partial class AddWfpComplianceAlert
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523182635_AddWfpScheduleChangeAndShiftSwap")]
    partial class AddWfpScheduleChangeAndShiftSwap
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526025344_initializeMstServiceUnit")]
    partial class initializeMstServiceUnit
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526030941_initializeMstClinic")]
    partial class initializeMstClinic
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526033017_initializeMstPatientClass")]
    partial class initializeMstPatientClass
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526034406_changeMstPatientClass")]
    partial class changeMstPatientClass
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526035908_initializeMstTariffCategory")]
    partial class initializeMstTariffCategory
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526040550_initializeMstTariff")]
    partial class initializeMstTariff
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526044345_initializeMstRoom")]
    partial class initializeMstRoom
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526045352_initializeMstBed")]
    partial class initializeMstBed
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526070146_AddPatientManagementMasterData")]
    partial class AddPatientManagementMasterData
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527120604_addMstInsuranceProvider")]
    partial class addMstInsuranceProvider
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527155218_addInsuranceAndCompanyGuarantor")]
    partial class addInsuranceAndCompanyGuarantor
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527165204_AddMstPaymentMethodAndMstBillingItemCategory")]
    partial class AddMstPaymentMethodAndMstBillingItemCategory
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527174229_addMasterMstProcedureMstDrugCategoryMstDrugMstInsuranceCoverageRule")]
    partial class addMasterMstProcedureMstDrugCategoryMstDrugMstInsuranceCoverageRule
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528074206_AddDrugAndProcedureMstTariff")]
    partial class AddDrugAndProcedureMstTariff
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529024939_addMstInsuranceTariff")]
    partial class addMstInsuranceTariff
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529163000_AddDoctorScheduleAndDoctorServiceRule")]
    partial class AddDoctorScheduleAndDoctorServiceRule
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260531153210_initializeTransactionPatient")]
    partial class initializeTransactionPatient
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601042244_changeDiagnoses")]
    partial class changeDiagnoses
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601051242_changeSizeDiagnosisName")]
    partial class changeSizeDiagnosisName
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601061704_test")]
    partial class test
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601072241_changePatientDoctorConsultant")]
    partial class changePatientDoctorConsultant
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601115030_AddChildDoctorConsultant1")]
    partial class AddChildDoctorConsultant1
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260602173235_changeEncounterPatientEntity")]
    partial class changeEncounterPatientEntity
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603175653_AddSupplierAndDrugSupplier")]
    partial class AddSupplierAndDrugSupplier
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605055922_dropColumnDefaultTariffProcedure")]
    partial class dropColumnDefaultTariffProcedure
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608075707_changeStructureBank")]
    partial class changeStructureBank
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608160339_changeStructureWfpInsuranceJoinInsurance")]
    partial class changeStructureWfpInsuranceJoinInsurance
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611072704_changeColumnKioskDevice")]
    partial class changeColumnKioskDevice
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260618113923_changeMasterPatient")]
    partial class changeMasterPatient
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260623185110_addcolumnQRCodePath")]
    partial class addcolumnQRCodePath
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625033243_initializeNurseStationCluster")]
    partial class initializeNurseStationCluster
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625034858_changeColumnQueueDisplay")]
    partial class changeColumnQueueDisplay
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629080609_initializeQueueVoiceProfil")]
    partial class initializeQueueVoiceProfil
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260630083659_adjustmentAgeCategory")]
    partial class adjustmentAgeCategory
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701035120_addColumnLingkarBayi")]
    partial class addColumnLingkarBayi
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701092047_addColumnPatientAssesment")]
    partial class addColumnPatientAssesment
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260703085847_addColumnAssessmentPatient")]
    partial class addColumnAssessmentPatient
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260704164927_changeColumnKioskDisplaySession")]
    partial class changeColumnKioskDisplaySession
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260704175511_changeColumnKioskDevice2")]
    partial class changeColumnKioskDevice2
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260704193224_changeColumnDisplayDevice")]
    partial class changeColumnDisplayDevice
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706092815_changeColumnDiagnosis")]
    partial class changeColumnDiagnosis
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260707041312_changeColumnRecomendation")]
    partial class changeColumnRecomendation
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260709045618_initializeTrxPatientIntegratedProgressNote")]
    partial class initializeTrxPatientIntegratedProgressNote
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260712123508_initializePrescriptionComponent")]
    partial class initializePrescriptionComponent
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260712165809_changeQueueCode")]
    partial class changeQueueCode
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260713181900_changeDrugStructure")]
    partial class changeDrugStructure
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260714183557_changeClusterEntity")]
    partial class changeClusterEntity
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715083359_changeColumnPrescriptionCompound")]
    partial class changeColumnPrescriptionCompound
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260716040410_initializeTelaahResep")]
    partial class initializeTelaahResep
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720030710_changePatientProcedureSchema")]
    partial class changePatientProcedureSchema
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260726161839_initializeBigModulHRD2")]
    partial class initializeBigModulHRD2
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260727034306_removeSortOrderPart1")]
    partial class removeSortOrderPart1
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729042559_changeColumnWfpDisciplinaryAction")]
    partial class changeColumnWfpDisciplinaryAction
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730050557_initializeTrxWorkflowApproverAssignments")]
    partial class initializeTrxWorkflowApproverAssignments
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731065340_initializeTrxAttendancePeriodAndTrxAttendanceSchedulerJob")]
    partial class initializeTrxAttendancePeriodAndTrxAttendanceSchedulerJob
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731082354_initialiazeleaveCorePeriodBalanceLedgerFoundationV1")]
    partial class initialiazeleaveCorePeriodBalanceLedgerFoundationV1
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731084748_initializeleaveAccrualCarryForwardFoundationV1")]
    partial class initializeleaveAccrualCarryForwardFoundationV1
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731091443_initializeleaveOpeningBalanceManualAdjustmentFoundationV1")]
    partial class initializeleaveOpeningBalanceManualAdjustmentFoundationV1
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803050303_initializeleaveCalendarAttendanceExecutionV1")]
    partial class initializeleaveCalendarAttendanceExecutionV1
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804071642_initializeEmergencyInstallationManagement")]
    partial class initializeEmergencyInstallationManagement
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804084717_initializeHardenOvertimePolicyAndRate4A2A")]
    partial class initializeHardenOvertimePolicyAndRate4A2A
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804092426_addOvertimeRequestAndPlanningFoundation4A3")]
    partial class addOvertimeRequestAndPlanningFoundation4A3
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260805074811_addOvertimeClosingSchedulerAndReconciliation4I")]
    partial class addOvertimeClosingSchedulerAndReconciliation4I
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806053234_addEssScheduleShiftSwapResignationR2")]
    partial class addEssScheduleShiftSwapResignationR2
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260807083112_AddAutomaticApplicationVersioning")]
    partial class AddAutomaticApplicationVersioning
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808040709_FinalApplicationVersioningV2")]
    partial class FinalApplicationVersioningV2
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814073820_MakeTriageMaxWaitingMinutesNullable")]
    partial class MakeTriageMaxWaitingMinutesNullable
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815103436_initializeLabOrder")]
    partial class initializeLabOrder
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815182350_renameEmployeeRecognitionToHrd")]
    partial class renameEmployeeRecognitionToHrd
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818084734_AddTriageSlaBreachMarker")]
    partial class AddTriageSlaBreachMarker
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260819092733_ChangeNameTrxAttendanceToHrdAttendance")]
    partial class ChangeNameTrxAttendanceToHrdAttendance
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820082909_AddDiscountPolicy")]
    partial class AddDiscountPolicy
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820084721_AddTaxAndRoomChargePolicies")]
    partial class AddTaxAndRoomChargePolicies
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820090951_AddRunningInvoiceAndIdempotentCharge")]
    partial class AddRunningInvoiceAndIdempotentCharge
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821020839_AllowOutOfQueueScaleTriageLevel")]
    partial class AllowOutOfQueueScaleTriageLevel
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821033911_AddBillingOperationalBaseline")]
    partial class AddBillingOperationalBaseline
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821034003_AddModulBackendBillingdanKasirPart1")]
    partial class AddModulBackendBillingdanKasirPart1
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821060256_AddOperatingRoomFoundation")]
    partial class AddOperatingRoomFoundation
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821063311_AddNosocomialInfection")]
    partial class AddNosocomialInfection
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821075926_NormalizeAttendanceCorrectionFamilyToHrd")]
    partial class NormalizeAttendanceCorrectionFamilyToHrd
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260822154039_RenameAttendancePersistenceToHrd")]
    partial class RenameAttendancePersistenceToHrd
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824053651_CreateInpatientMasterTables")]
    partial class CreateInpatientMasterTables
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824074649_AddClinicalMilestoneFactHandoff")]
    partial class AddClinicalMilestoneFactHandoff
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824080052_AddBackendBillingDanKasirPart2")]
    partial class AddBackendBillingDanKasirPart2
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824080430_StoreClinicalFactSnapshotAsText")]
    partial class StoreClinicalFactSnapshotAsText
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824082058_EditMaxLeghtModuleCode")]
    partial class EditMaxLeghtModuleCode
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824091610_AddLaboratorySpecimenLifecycle")]
    partial class AddLaboratorySpecimenLifecycle
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824095353_CreateInpatientTransactionTables")]
    partial class CreateInpatientTransactionTables
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826025451_AddTableBillingKasirPArt3")]
    partial class AddTableBillingKasirPArt3
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826090500_ImplementIgdFullPatientJourney")]
    partial class ImplementIgdFullPatientJourney
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827030000_RenameEmergencyDepartureToEmgPrefix")]
    partial class RenameEmergencyDepartureToEmgPrefix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827040000_RenameEmergencyMasterDataToEmgPrefix")]
    partial class RenameEmergencyMasterDataToEmgPrefix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827050000_RenameEmergencyTriageDetailToEmgPrefix")]
    partial class RenameEmergencyTriageDetailToEmgPrefix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827060000_RenameEmergencyOperationalToEmgPrefix")]
    partial class RenameEmergencyOperationalToEmgPrefix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260828063909_RepairCanonicalEfModelBaseline")]
    partial class RepairCanonicalEfModelBaseline
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260828093000_AddRadiologyManagement")]
    partial class AddRadiologyManagement
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260830151340_RepairPostCanonicalIntegration")]
    partial class RepairPostCanonicalIntegration
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831000000_RenameMedicalRecordTrxTablesToMrcPrefix")]
    partial class RenameMedicalRecordTrxTablesToMrcPrefix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831075231_AddCompanyGuarantorToPatientEncounterGuarantor")]
    partial class AddCompanyGuarantorToPatientEncounterGuarantor
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901041805_RenameClinicalMilestoneFactToCliPrefix")]
    partial class RenameClinicalMilestoneFactToCliPrefix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901081830_AddNutritionManagement")]
    partial class AddNutritionManagement
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901082243_AddBilTenderKwitansiNumber")]
    partial class AddBilTenderKwitansiNumber
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901094255_RepairCanonicalModelSnapshotBaseline")]
    partial class RepairCanonicalModelSnapshotBaseline
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902031305_AddPharmacyStockRequest")]
    partial class AddPharmacyStockRequest
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902042242_AddLabOrderDiscipline")]
    partial class AddLabOrderDiscipline
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902072756_DropTableMstBillingCategory")]
    partial class DropTableMstBillingCategory
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902081432_AddAccountingFoundation")]
    partial class AddAccountingFoundation
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902082722_AddLabValueBoundAndOption")]
    partial class AddLabValueBoundAndOption
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902085636_AddLabValueBoundApprovalAndHistory")]
    partial class AddLabValueBoundApprovalAndHistory
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902091736_AmendLabValueBoundUniquenessAndSortOrder")]
    partial class AmendLabValueBoundUniquenessAndSortOrder
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903015730_AddTariffIdToBilInvoiceItem")]
    partial class AddTariffIdToBilInvoiceItem
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903044753_AddMstBloodComponent")]
    partial class AddMstBloodComponent
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903054859_AddPharmacyDrugStockFoundation")]
    partial class AddPharmacyDrugStockFoundation
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903060228_AddServiceUnitBloodOrderFlag")]
    partial class AddServiceUnitBloodOrderFlag
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903064435_FixDrugBatchSupplierReference")]
    partial class FixDrugBatchSupplierReference
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903071535_AddLabExamination")]
    partial class AddLabExamination
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903081732_AddPharmacyStockTransfer")]
    partial class AddPharmacyStockTransfer
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903082426_AddStockTransferAllocationSequence")]
    partial class AddStockTransferAllocationSequence
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903083142_AddMstBloodStorageLocation")]
    partial class AddMstBloodStorageLocation
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903085417_AddPharmacyDrugUsage")]
    partial class AddPharmacyDrugUsage
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903091743_AddPharmacyDrugReturn")]
    partial class AddPharmacyDrugReturn
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903092936_AddInpatientClinicalContextColumns")]
    partial class AddInpatientClinicalContextColumns
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903093431_AddMstBloodBankReason")]
    partial class AddMstBloodBankReason
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903093510_AddCliPhysicianVisit")]
    partial class AddCliPhysicianVisit
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903094528_RenameLaboratoryTrxTablesToLabPrefix")]
    partial class RenameLaboratoryTrxTablesToLabPrefix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903094734_AddPrescriptionInpatientContext")]
    partial class AddPrescriptionInpatientContext
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903095022_AddLabOrderInpatientContext")]
    partial class AddLabOrderInpatientContext
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903095444_AddRadOrderInpatientContext")]
    partial class AddRadOrderInpatientContext
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903100128_RelaxSingleConsultationAndPrescriptionForInpatient")]
    partial class RelaxSingleConsultationAndPrescriptionForInpatient
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903163000_FixTariffCategoryInsuranceCoverageDefault")]
    partial class FixTariffCategoryInsuranceCoverageDefault
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904030116_SplitLabSpecimenIntoExamination")]
    partial class SplitLabSpecimenIntoExamination
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904035620_AddLabExaminationIdToLabTransitionHistory")]
    partial class AddLabExaminationIdToLabTransitionHistory
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904045422_AddOperatingRoomStockSourceAndMaterialUnit")]
    partial class AddOperatingRoomStockSourceAndMaterialUnit
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904065309_AddLabDisciplineAndReferralMasterData")]
    partial class AddLabDisciplineAndReferralMasterData
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904072427_AddReferralPointerToPatientEncounter")]
    partial class AddReferralPointerToPatientEncounter
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904232421_AddWriteOffCategoryAndNonBillableResidual")]
    partial class AddWriteOffCategoryAndNonBillableResidual
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905081108_AddMedicalAssessmentContentColumns")]
    partial class AddMedicalAssessmentContentColumns
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905090533_AddAssessmentDueAtAndPolicyId")]
    partial class AddAssessmentDueAtAndPolicyId
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260906121936_AddClinicalAssessmentPolicyMaster")]
    partial class AddClinicalAssessmentPolicyMaster
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260906122534_AddInitialNursingAssessmentPartialIndex")]
    partial class AddInitialNursingAssessmentPartialIndex
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260906144058_AddNursingCarePlan")]
    partial class AddNursingCarePlan
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260906144956_AddNursingCarePlanItemRevision")]
    partial class AddNursingCarePlanItemRevision
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260906151002_AddNursingIntervention")]
    partial class AddNursingIntervention
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907040000_AddPharmacyPrescriptionDispensingLink")]
    partial class AddPharmacyPrescriptionDispensingLink
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907045236_AddPharmacyPrescriptionCopy")]
    partial class AddPharmacyPrescriptionCopy
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907072413_AddRegistrationIdempotencyKeyToPatientEncounter")]
    partial class AddRegistrationIdempotencyKeyToPatientEncounter
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908000000_RenamePharmacyTrxTablesToPhmPrefix")]
    partial class RenamePharmacyTrxTablesToPhmPrefix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909000000_RenameDrugBatchAndOperatingRoomStockSource")]
    partial class RenameDrugBatchAndOperatingRoomStockSource
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909015603_AddBbkBloodGroupExam")]
    partial class AddBbkBloodGroupExam
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909060515_AddAccountingPhase2Independent")]
    partial class AddAccountingPhase2Independent
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909060735_AddTableDepositPolicy")]
    partial class AddTableDepositPolicy
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909065125_AddInpatientEpisodeContextToPatientDiagnosis")]
    partial class AddInpatientEpisodeContextToPatientDiagnosis
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909070218_AddNumNumberSeries")]
    partial class AddNumNumberSeries
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909075500_RenameTrxPatientEncounterGuarantorToRegPrefix")]
    partial class RenameTrxPatientEncounterGuarantorToRegPrefix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910030523_AddRadSafetyRuleApprovalLifecycle")]
    partial class AddRadSafetyRuleApprovalLifecycle
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910031500_RenameTrxPatientEncounterAndPrescriptionToCanonicalPrefix")]
    partial class RenameTrxPatientEncounterAndPrescriptionToCanonicalPrefix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910041922_AddDepositFollowUpIntervalToInpatientSetting")]
    partial class AddDepositFollowUpIntervalToInpatientSetting
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910061742_AddTableMstPaymentMethodAccAndChangeTrfPerfix")]
    partial class AddTableMstPaymentMethodAccAndChangeTrfPerfix
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910153119_AddBbkBloodOrder")]
    partial class AddBbkBloodOrder
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911025734_AddRadReport")]
    partial class AddRadReport
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911032311_AddBbkProviderRequestAndBloodUnit")]
    partial class AddBbkProviderRequestAndBloodUnit
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911045053_AddRadOrderUrgency")]
    partial class AddRadOrderUrgency
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911070236_AddCompanyGuarantorAndItemPayerFoundation")]
    partial class AddCompanyGuarantorAndItemPayerFoundation
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911072451_AddBbkBloodBankProcedure")]
    partial class AddBbkBloodBankProcedure
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911081156_AddRadOrderNumber")]
    partial class AddRadOrderNumber
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911090848_AddBbkBloodUnitPlacement")]
    partial class AddBbkBloodUnitPlacement
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260913070556_AddBbkBloodUnitAllocation")]
    partial class AddBbkBloodUnitAllocation
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260914044507_AddAccountingPostingRuleMaster")]
    partial class AddAccountingPostingRuleMaster
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260914084655_AddLabSpecimenType")]
    partial class AddLabSpecimenType
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260914084730_SeedLabSpecimenType")]
    partial class SeedLabSpecimenType
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260914090021_AddBloodCompatibilityEvidenceAndIssuance")]
    partial class AddBloodCompatibilityEvidenceAndIssuance
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915035317_AddLabSpecimenTypeAndVolumeColumns")]
    partial class AddLabSpecimenTypeAndVolumeColumns
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915042458_AddLabSpecimenPhysicallyReceivedAt")]
    partial class AddLabSpecimenPhysicallyReceivedAt
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915081317_AddLabOrderedProcedure")]
    partial class AddLabOrderedProcedure
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915083316_AddKioskServiceTargetAndPhysicianRequest")]
    partial class AddKioskServiceTargetAndPhysicianRequest
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260916022245_AddLabOrderConfirmation")]
    partial class AddLabOrderConfirmation
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260916051204_AddBbkEmergencyAuthorization")]
    partial class AddBbkEmergencyAuthorization
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917021029_AddBbkCompatibilityEvidenceSupersededReason")]
    partial class AddBbkCompatibilityEvidenceSupersededReason
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917023651_AddLabOrderNumber")]
    partial class AddLabOrderNumber
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917055332_AddBbkIssuanceCorrection")]
    partial class AddBbkIssuanceCorrection
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917065900_AddLabExaminationResultEntry")]
    partial class AddLabExaminationResultEntry
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917083800_AddFundingSourceToPettyCashMovement")]
    partial class AddFundingSourceToPettyCashMovement
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918060130_AddLabPathologyMasterData")]
    partial class AddLabPathologyMasterData
    {
    }

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918063610_RemoveTaxableCategoryFromMstTaxRule")]
    partial class RemoveTaxableCategoryFromMstTaxRule
    {
    }
}
