using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuilvianSystemBackend.Areas.Corporate.HumanResource.MasterData.CompetencyAndCredential.DTOs;
using QuilvianSystemBackend.Areas.Corporate.HumanResource.MasterData.CompetencyAndCredential.Models;
using QuilvianSystemBackend.Attributes;
using QuilvianSystemBackend.Constants;
using QuilvianSystemBackend.Repositories;
using QuilvianSystemBackend.Responses;
using QuilvianSystemBackend.Services.Logging;
using System.Security.Claims;

using QuilvianSystemBackend.Areas.Corporate.HumanResource.LearningAndDevelopment.Models;
using QuilvianSystemBackend.Areas.Corporate.HumanResource.MasterData.Organization.Models;
using QuilvianSystemBackend.Areas.Corporate.HumanResource.MasterData.Workforce.Models;
using MandatoryRulePagedResult = QuilvianSystemBackend.Responses.PagedResult<QuilvianSystemBackend.Areas.Corporate.HumanResource.MasterData.CompetencyAndCredential.DTOs.MandatoryTrainingRuleResponse>;

namespace QuilvianSystemBackend.Areas.Corporate.HumanResource.MasterData.CompetencyAndCredential.Controllers
{
    [ApiController,Authorize]
    [Route("api/v1/corporate/human-resource/master-data/mandatory-training-rules")]
    [AccessController("HUMAN_RESOURCE_MASTER_DATA","Human Resource Master Data","Mandatory Training Rule",AreaName="Corporate",ControllerName="MandatoryTrainingRule",Description="Corporate human resource master data mandatory training rule",SortOrder=23)]
    [Tags("Corporate / Human Resource / Master Data / Mandatory Training Rule")]
    public class MandatoryTrainingRuleController:ControllerBase
    {
        private const string Prefix="MTR-RSMMC-"; private readonly ApplicationDbContext _db; private readonly LoggerService _log; public MandatoryTrainingRuleController(ApplicationDbContext db,LoggerService log){_db=db;_log=log;}
        [HttpGet("filters/metadata"),AccessAction("Read","Read Mandatory Training Rule",Description="Melihat metadata filter mandatory training rule",AccessType=AccessTypes.Read,SortOrder=1),AccessPermission("MandatoryTrainingRule","Read")]
        public IActionResult Metadata()=>Ok(ApiResponse<MandatoryTrainingRuleFilterMetadataResponse>.Ok(new(){DefaultFilter=new(),CustomPeriods=Periods(),SortDirections=new(){"asc","desc"},PageSizeOptions=new(){10,25,50,100},SortOptions=new(){new(){Value="createDateTime",Label="Tanggal dibuat"},new(){Value="ruleCode",Label="Kode aturan"},new(){Value="ruleName",Label="Nama aturan"},new(){Value="trainingName",Label="Nama pelatihan"},new(){Value="priority",Label="Prioritas"},new(){Value="effectiveStartDate",Label="Tanggal mulai berlaku"},new(){Value="isActive",Label="Status aktif"}}},"Metadata filter mandatory training rule berhasil diambil."));
        [HttpGet("summary"),AccessAction("Read","Read Mandatory Training Rule",Description="Melihat ringkasan mandatory training rule",AccessType=AccessTypes.Read,SortOrder=1),AccessPermission("MandatoryTrainingRule","Read")]
        public async Task<IActionResult> Summary(CancellationToken ct){var q=Base();var today=DateTime.UtcNow.Date;return Ok(ApiResponse<MandatoryTrainingRuleSummaryResponse>.Ok(new(){TotalRule=await q.CountAsync(ct),ActiveRule=await q.CountAsync(x=>x.IsActive,ct),InactiveRule=await q.CountAsync(x=>!x.IsActive,ct),CurrentlyEffectiveRule=await q.CountAsync(x=>x.IsActive&&(!x.EffectiveStartDate.HasValue||x.EffectiveStartDate<=today)&&(!x.EffectiveEndDate.HasValue||x.EffectiveEndDate>=today),ct),CredentialingRequiredRule=await q.CountAsync(x=>x.IsRequiredForCredentialing,ct),IndependentPracticeRequiredRule=await q.CountAsync(x=>x.IsRequiredBeforeIndependentPractice,ct),PassingResultRequiredRule=await q.CountAsync(x=>x.RequiresPassingResult,ct),RecurringRule=await q.CountAsync(x=>x.RecurrenceMonths.HasValue,ct)},"Ringkasan mandatory training rule berhasil diambil."));}
        [HttpGet,AccessAction("Read","Read Mandatory Training Rule",Description="Melihat data mandatory training rule",AccessType=AccessTypes.Read,SortOrder=1),AccessPermission("MandatoryTrainingRule","Read")]
        public async Task<IActionResult> Get([FromQuery]DateTime? startDate,[FromQuery]DateTime? endDate,[FromQuery]string? customPeriod,[FromQuery]Guid? trainingCatalogId,[FromQuery]Guid? legalEntityId,[FromQuery]Guid? hospitalSiteId,[FromQuery]Guid? organizationUnitId,[FromQuery]Guid? positionId,[FromQuery]Guid? professionId,[FromQuery]Guid? specializationId,[FromQuery]Guid? employeeCategoryId,[FromQuery]Guid? employmentTypeId,[FromQuery]bool? isRequiredForCredentialing,[FromQuery]bool? isRequiredBeforeIndependentPractice,[FromQuery]bool? requiresPassingResult,[FromQuery]bool? isCurrentlyEffective,[FromQuery]bool? isActive,[FromQuery]string? search,[FromQuery]string? sortBy="priority",[FromQuery]string? sortDirection="desc",[FromQuery]int pageNumber=1,[FromQuery]int pageSize=25,CancellationToken ct=default){Page(ref pageNumber,ref pageSize);var q=Date(Base(),startDate,endDate,customPeriod);q=Filter(q,trainingCatalogId,legalEntityId,hospitalSiteId,organizationUnitId,positionId,professionId,specializationId,employeeCategoryId,employmentTypeId,isRequiredForCredentialing,isRequiredBeforeIndependentPractice,requiresPassingResult,isCurrentlyEffective,isActive,search);var total=await q.CountAsync(ct);var list=await Sort(q,sortBy,sortDirection).Skip((pageNumber-1)*pageSize).Take(pageSize).ToListAsync(ct);var a=await Actors(list.Select(x=>x.CreateBy),ct);return Ok(ApiResponse<MandatoryRulePagedResult>.Ok(new(){PageNumber=pageNumber,PageSize=pageSize,TotalData=total,TotalPage=(int)Math.Ceiling(total/(double)pageSize),Items=list.Select(x=>Map(x,a)).ToList()},"Data mandatory training rule berhasil diambil."));}
        [HttpGet("options"),AccessAction("Read","Read Mandatory Training Rule",Description="Melihat pilihan mandatory training rule",AccessType=AccessTypes.Read,SortOrder=1),AccessPermission("MandatoryTrainingRule","Read")]
        public async Task<IActionResult> Options([FromQuery]Guid? trainingCatalogId,[FromQuery]Guid? professionId,[FromQuery]Guid? positionId,[FromQuery]bool onlyEffective=true,[FromQuery]string? search=null,[FromQuery]int pageNumber=1,[FromQuery]int pageSize=25,CancellationToken ct=default){Page(ref pageNumber,ref pageSize);var q=Filter(Base(),trainingCatalogId,null,null,null,positionId,professionId,null,null,null,null,null,null,onlyEffective?true:null,true,search);var total=await q.CountAsync(ct);var items=await q.OrderByDescending(x=>x.Priority).ThenBy(x=>x.RuleName).Skip((pageNumber-1)*pageSize).Take(pageSize).Select(x=>new MandatoryTrainingRuleOptionResponse{Id=x.Id,TrainingCatalogId=x.TrainingCatalogId,TrainingName=x.TrainingCatalog!=null?x.TrainingCatalog.TrainingName:string.Empty,RuleCode=x.RuleCode,RuleName=x.RuleName,CompletionDueDaysFromJoin=x.CompletionDueDaysFromJoin,RecurrenceMonths=x.RecurrenceMonths,GracePeriodDays=x.GracePeriodDays,RequiresPassingResult=x.RequiresPassingResult,MinimumPassingScore=x.MinimumPassingScore,EffectiveStartDate=x.EffectiveStartDate,EffectiveEndDate=x.EffectiveEndDate,Priority=x.Priority}).ToListAsync(ct);return Ok(ApiResponse<MandatoryTrainingRuleOptionPagedResponse>.Ok(new(){PageNumber=pageNumber,PageSize=pageSize,TotalData=total,TotalPage=(int)Math.Ceiling(total/(double)pageSize),Items=items},"Pilihan mandatory training rule berhasil diambil."));}
        [HttpGet("{id:guid}"),AccessAction("Read","Read Mandatory Training Rule",Description="Melihat detail mandatory training rule",AccessType=AccessTypes.Read,SortOrder=1),AccessPermission("MandatoryTrainingRule","Read")]
        public async Task<IActionResult> Detail(Guid id,CancellationToken ct){var x=await Base().FirstOrDefaultAsync(x=>x.Id==id,ct);if(x==null)return NotFound(ApiResponse<object>.Fail(404,"Mandatory training rule tidak ditemukan."));var a=await Actors(new[]{x.CreateBy,x.UpdateBy},ct);var b=Map(x,a);var r=new MandatoryTrainingRuleDetailResponse();foreach(var p in typeof(MandatoryTrainingRuleResponse).GetProperties())p.SetValue(r,p.GetValue(b));r.UpdateDateTime=x.UpdateDateTime;r.UpdateBy=x.UpdateBy==Guid.Empty?null:x.UpdateBy;r.UpdateByName=Actor(a,x.UpdateBy);return Ok(ApiResponse<MandatoryTrainingRuleDetailResponse>.Ok(r,"Detail mandatory training rule berhasil diambil."));}
        [HttpPost,AccessAction("Create","Create Mandatory Training Rule",Description="Membuat mandatory training rule",AccessType=AccessTypes.Create,SortOrder=2),AccessPermission("MandatoryTrainingRule","Create")]
        public async Task<IActionResult> Create([FromBody]CreateMandatoryTrainingRuleRequest r,CancellationToken ct){var v=await Validate(null,r,ct);if(!v.ok)return BadRequest(ApiResponse<object>.Fail(400,v.error!));var e=new MstMandatoryTrainingRule{Id=Guid.NewGuid(),TrainingCatalogId=r.TrainingCatalogId,LegalEntityId=G(r.LegalEntityId),HospitalSiteId=G(r.HospitalSiteId),OrganizationUnitId=G(r.OrganizationUnitId),PositionId=G(r.PositionId),ProfessionId=G(r.ProfessionId),SpecializationId=G(r.SpecializationId),EmployeeCategoryId=G(r.EmployeeCategoryId),EmploymentTypeId=G(r.EmploymentTypeId),RuleCode=await Code(ct),RuleName=r.RuleName.Trim(),CompletionDueDaysFromJoin=r.CompletionDueDaysFromJoin,RecurrenceMonths=r.RecurrenceMonths,GracePeriodDays=r.GracePeriodDays,IsRequiredBeforeAssignment=r.IsRequiredBeforeAssignment,IsRequiredForCredentialing=r.IsRequiredForCredentialing,IsRequiredBeforeIndependentPractice=r.IsRequiredBeforeIndependentPractice,RequiresPassingResult=r.RequiresPassingResult,MinimumPassingScore=r.RequiresPassingResult?r.MinimumPassingScore:null,EffectiveStartDate=r.EffectiveStartDate?.Date,EffectiveEndDate=r.EffectiveEndDate?.Date,Priority=r.Priority,Description=T(r.Description),IsActive=true,CreateDateTime=DateTime.UtcNow,CreateBy=Uid(),IsDelete=false,IsCancel=false};_db.Set<MstMandatoryTrainingRule>().Add(e);await _db.SaveChangesAsync(ct);await _log.InfoAsync("Corporate.HumanResource.MasterData","MandatoryTrainingRule.Create","Membuat mandatory training rule.",new{e.Id,e.RuleCode,e.RuleName});return Ok(ApiResponse<MandatoryTrainingRuleCreateResponse>.Ok(new(){Id=e.Id,RuleCode=e.RuleCode,RuleName=e.RuleName,IsActive=e.IsActive},"Mandatory training rule berhasil dibuat."));}
        [HttpPut("{id:guid}"),AccessAction("Update","Update Mandatory Training Rule",Description="Mengubah mandatory training rule",AccessType=AccessTypes.Update,SortOrder=3),AccessPermission("MandatoryTrainingRule","Update")]
        public async Task<IActionResult> Update(Guid id,[FromBody]UpdateMandatoryTrainingRuleRequest r,CancellationToken ct){var e=await Find(id,ct);if(e==null)return NotFound(ApiResponse<object>.Fail(404,"Mandatory training rule tidak ditemukan."));var v=await Validate(id,r,ct);if(!v.ok)return BadRequest(ApiResponse<object>.Fail(400,v.error!));e.TrainingCatalogId=r.TrainingCatalogId;e.LegalEntityId=G(r.LegalEntityId);e.HospitalSiteId=G(r.HospitalSiteId);e.OrganizationUnitId=G(r.OrganizationUnitId);e.PositionId=G(r.PositionId);e.ProfessionId=G(r.ProfessionId);e.SpecializationId=G(r.SpecializationId);e.EmployeeCategoryId=G(r.EmployeeCategoryId);e.EmploymentTypeId=G(r.EmploymentTypeId);e.RuleName=r.RuleName.Trim();e.CompletionDueDaysFromJoin=r.CompletionDueDaysFromJoin;e.RecurrenceMonths=r.RecurrenceMonths;e.GracePeriodDays=r.GracePeriodDays;e.IsRequiredBeforeAssignment=r.IsRequiredBeforeAssignment;e.IsRequiredForCredentialing=r.IsRequiredForCredentialing;e.IsRequiredBeforeIndependentPractice=r.IsRequiredBeforeIndependentPractice;e.RequiresPassingResult=r.RequiresPassingResult;e.MinimumPassingScore=r.RequiresPassingResult?r.MinimumPassingScore:null;e.EffectiveStartDate=r.EffectiveStartDate?.Date;e.EffectiveEndDate=r.EffectiveEndDate?.Date;e.Priority=r.Priority;e.Description=T(r.Description);e.IsActive=r.IsActive;e.UpdateDateTime=DateTime.UtcNow;e.UpdateBy=Uid();await _db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.Ok(null,"Mandatory training rule berhasil diperbarui."));}
        [HttpPatch("{id:guid}/status"),AccessAction("Update","Update Mandatory Training Rule Status",Description="Mengubah status mandatory training rule",AccessType=AccessTypes.Update,SortOrder=4),AccessPermission("MandatoryTrainingRule","Update")]
        public async Task<IActionResult> Status(Guid id,[FromBody]UpdateMandatoryTrainingRuleStatusRequest r,CancellationToken ct){var e=await Find(id,ct);if(e==null)return NotFound(ApiResponse<object>.Fail(404,"Mandatory training rule tidak ditemukan."));e.IsActive=r.IsActive;e.UpdateDateTime=DateTime.UtcNow;e.UpdateBy=Uid();await _db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.Ok(null,"Status mandatory training rule berhasil diperbarui."));}
        [HttpDelete("{id:guid}"),AccessAction("Delete","Delete Mandatory Training Rule",Description="Menghapus mandatory training rule",AccessType=AccessTypes.Delete,SortOrder=5),AccessPermission("MandatoryTrainingRule","Delete")]
        public async Task<IActionResult> Delete(Guid id,CancellationToken ct){var e=await Find(id,ct);if(e==null)return NotFound(ApiResponse<object>.Fail(404,"Mandatory training rule tidak ditemukan."));if(await _db.Set<WfpTrainingRecord>().AnyAsync(x=>x.MandatoryTrainingRuleId==id&&!x.IsDelete,ct))return BadRequest(ApiResponse<object>.Fail(400,"Mandatory training rule tidak dapat dihapus karena sudah digunakan oleh training record."));var n=DateTime.UtcNow;var a=Uid();e.IsDelete=true;e.IsActive=false;e.DeleteDateTime=n;e.DeleteBy=a;e.UpdateDateTime=n;e.UpdateBy=a;await _db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.Ok(null,"Mandatory training rule berhasil dihapus."));}
        private IQueryable<MstMandatoryTrainingRule> Base()=>_db.Set<MstMandatoryTrainingRule>().AsNoTracking().Include(x=>x.TrainingCatalog).ThenInclude(x=>x!.TrainingCategory).Include(x=>x.Position).Include(x=>x.Profession).Include(x=>x.Specialization).Include(x=>x.EmployeeCategory).Include(x=>x.EmploymentType).Where(x=>!x.IsDelete);
        private async Task<MstMandatoryTrainingRule?> Find(Guid id,CancellationToken ct)=>await _db.Set<MstMandatoryTrainingRule>().FirstOrDefaultAsync(x=>x.Id==id&&!x.IsDelete,ct);
        private async Task<(bool ok,string? error)> Validate(Guid? id,CreateMandatoryTrainingRuleRequest r,CancellationToken ct){if(r.TrainingCatalogId==Guid.Empty||!await Active<MstTrainingCatalog>(r.TrainingCatalogId,ct))return(false,"Training catalog tidak ditemukan atau tidak aktif.");if(string.IsNullOrWhiteSpace(r.RuleName))return(false,"Nama aturan wajib diisi.");if(r.CompletionDueDaysFromJoin<0||r.GracePeriodDays<0||r.Priority<0)return(false,"Nilai hari dan priority tidak boleh negatif.");if(r.RecurrenceMonths.HasValue&&r.RecurrenceMonths<=0)return(false,"Recurrence months harus lebih dari 0.");if(r.EffectiveEndDate.HasValue&&r.EffectiveStartDate.HasValue&&r.EffectiveEndDate.Value<r.EffectiveStartDate.Value)return(false,"Tanggal selesai berlaku tidak boleh lebih kecil dari tanggal mulai.");if(r.RequiresPassingResult&&!r.MinimumPassingScore.HasValue)return(false,"Minimum passing score wajib jika passing result diperlukan.");if(r.MinimumPassingScore is <0 or >100)return(false,"Minimum passing score harus antara 0 dan 100.");if(!await Opt<MstLegalEntity>(r.LegalEntityId,ct))return(false,"Legal entity tidak ditemukan atau tidak aktif.");if(!await Opt<MstHospitalSite>(r.HospitalSiteId,ct))return(false,"Hospital site tidak ditemukan atau tidak aktif.");if(!await Opt<MstOrganizationUnit>(r.OrganizationUnitId,ct))return(false,"Organization unit tidak ditemukan atau tidak aktif.");if(!await Opt<MstPosition>(r.PositionId,ct))return(false,"Position tidak ditemukan atau tidak aktif.");if(!await Opt<MstProfession>(r.ProfessionId,ct))return(false,"Profession tidak ditemukan atau tidak aktif.");if(!await Opt<MstSpecialization>(r.SpecializationId,ct))return(false,"Specialization tidak ditemukan atau tidak aktif.");if(!await Opt<MstEmployeeCategory>(r.EmployeeCategoryId,ct))return(false,"Employee category tidak ditemukan atau tidak aktif.");if(!await Opt<MstEmploymentType>(r.EmploymentTypeId,ct))return(false,"Employment type tidak ditemukan atau tidak aktif.");if(r.SpecializationId.HasValue&&r.ProfessionId.HasValue&&!await _db.Set<MstSpecialization>().AnyAsync(x=>x.Id==r.SpecializationId&&x.ProfessionId==r.ProfessionId&&!x.IsDelete,ct))return(false,"Specialization tidak sesuai dengan profession.");var q=_db.Set<MstMandatoryTrainingRule>().AsNoTracking().Where(x=>!x.IsDelete&&x.TrainingCatalogId==r.TrainingCatalogId&&x.RuleName.ToLower()==r.RuleName.Trim().ToLower()&&x.PositionId==G(r.PositionId)&&x.ProfessionId==G(r.ProfessionId)&&x.SpecializationId==G(r.SpecializationId));if(id.HasValue)q=q.Where(x=>x.Id!=id);if(await q.AnyAsync(ct))return(false,"Aturan dengan scope dan nama yang sama sudah tersedia.");return(true,null);}
        private async Task<bool> Active<TModel>(Guid id,CancellationToken ct) where TModel:QuilvianSystemBackend.Models.IdentityModel=>await _db.Set<TModel>().AnyAsync(x=>EF.Property<Guid>(x,"Id")==id&&EF.Property<bool>(x,"IsActive")&&!EF.Property<bool>(x,"IsDelete"),ct);private async Task<bool> Opt<TModel>(Guid? id,CancellationToken ct) where TModel:QuilvianSystemBackend.Models.IdentityModel=>!id.HasValue||id==Guid.Empty||await Active<TModel>(id.Value,ct);
        private MandatoryTrainingRuleResponse Map(MstMandatoryTrainingRule x,IReadOnlyDictionary<Guid,string>a){var t=DateTime.UtcNow.Date;return new(){Id=x.Id,TrainingCatalogId=x.TrainingCatalogId,TrainingCode=x.TrainingCatalog?.TrainingCode??string.Empty,TrainingName=x.TrainingCatalog?.TrainingName??string.Empty,TrainingCategoryId=x.TrainingCatalog?.TrainingCategoryId??Guid.Empty,TrainingCategoryName=x.TrainingCatalog?.TrainingCategory?.TrainingCategoryName??string.Empty,LegalEntityId=x.LegalEntityId,HospitalSiteId=x.HospitalSiteId,OrganizationUnitId=x.OrganizationUnitId,PositionId=x.PositionId,PositionName=x.Position?.PositionName,ProfessionId=x.ProfessionId,ProfessionName=x.Profession?.ProfessionName,SpecializationId=x.SpecializationId,SpecializationName=x.Specialization?.SpecializationName,EmployeeCategoryId=x.EmployeeCategoryId,EmployeeCategoryName=x.EmployeeCategory?.EmployeeCategoryName,EmploymentTypeId=x.EmploymentTypeId,EmploymentTypeName=x.EmploymentType?.EmploymentTypeName,RuleCode=x.RuleCode,RuleName=x.RuleName,CompletionDueDaysFromJoin=x.CompletionDueDaysFromJoin,RecurrenceMonths=x.RecurrenceMonths,GracePeriodDays=x.GracePeriodDays,IsRequiredBeforeAssignment=x.IsRequiredBeforeAssignment,IsRequiredForCredentialing=x.IsRequiredForCredentialing,IsRequiredBeforeIndependentPractice=x.IsRequiredBeforeIndependentPractice,RequiresPassingResult=x.RequiresPassingResult,MinimumPassingScore=x.MinimumPassingScore,EffectiveStartDate=x.EffectiveStartDate,EffectiveEndDate=x.EffectiveEndDate,IsCurrentlyEffective=x.IsActive&&(!x.EffectiveStartDate.HasValue||x.EffectiveStartDate<=t)&&(!x.EffectiveEndDate.HasValue||x.EffectiveEndDate>=t),Priority=x.Priority,Description=x.Description,IsActive=x.IsActive,WorkforceTrainingRecordCount=_db.Set<WfpTrainingRecord>().Count(r=>r.MandatoryTrainingRuleId==x.Id&&!r.IsDelete),CreateDateTime=x.CreateDateTime,CreateBy=x.CreateBy==Guid.Empty?null:x.CreateBy,CreateByName=Actor(a,x.CreateBy)};}
        private IQueryable<MstMandatoryTrainingRule> Filter(IQueryable<MstMandatoryTrainingRule>q,Guid? catalog,Guid? legal,Guid? site,Guid? unit,Guid? pos,Guid? prof,Guid? spec,Guid? cat,Guid? type,bool? cred,bool? indep,bool? pass,bool? current,bool? active,string? search){if(catalog.HasValue)q=q.Where(x=>x.TrainingCatalogId==catalog);if(legal.HasValue)q=q.Where(x=>x.LegalEntityId==legal);if(site.HasValue)q=q.Where(x=>x.HospitalSiteId==site);if(unit.HasValue)q=q.Where(x=>x.OrganizationUnitId==unit);if(pos.HasValue)q=q.Where(x=>x.PositionId==pos);if(prof.HasValue)q=q.Where(x=>x.ProfessionId==prof);if(spec.HasValue)q=q.Where(x=>x.SpecializationId==spec);if(cat.HasValue)q=q.Where(x=>x.EmployeeCategoryId==cat);if(type.HasValue)q=q.Where(x=>x.EmploymentTypeId==type);if(cred.HasValue)q=q.Where(x=>x.IsRequiredForCredentialing==cred);if(indep.HasValue)q=q.Where(x=>x.IsRequiredBeforeIndependentPractice==indep);if(pass.HasValue)q=q.Where(x=>x.RequiresPassingResult==pass);if(active.HasValue)q=q.Where(x=>x.IsActive==active);if(current.HasValue){var t=DateTime.UtcNow.Date;q=current.Value?q.Where(x=>x.IsActive&&(!x.EffectiveStartDate.HasValue||x.EffectiveStartDate<=t)&&(!x.EffectiveEndDate.HasValue||x.EffectiveEndDate>=t)):q.Where(x=>!x.IsActive||(x.EffectiveStartDate.HasValue&&x.EffectiveStartDate>t)||(x.EffectiveEndDate.HasValue&&x.EffectiveEndDate<t));}if(!string.IsNullOrWhiteSpace(search)){var k=search.Trim().ToLower();q=q.Where(x=>x.RuleCode.ToLower().Contains(k)||x.RuleName.ToLower().Contains(k)||(x.TrainingCatalog!=null&&x.TrainingCatalog.TrainingName.ToLower().Contains(k)));}return q;}
        private static IOrderedQueryable<MstMandatoryTrainingRule> Sort(IQueryable<MstMandatoryTrainingRule>q,string? by,string? dir){var d=string.Equals(dir,"desc",StringComparison.OrdinalIgnoreCase);return(by??"priority").ToLowerInvariant() switch{"createdatetime"=>d?q.OrderByDescending(x=>x.CreateDateTime):q.OrderBy(x=>x.CreateDateTime),"rulecode"=>d?q.OrderByDescending(x=>x.RuleCode):q.OrderBy(x=>x.RuleCode),"rulename"=>d?q.OrderByDescending(x=>x.RuleName):q.OrderBy(x=>x.RuleName),"trainingname"=>d?q.OrderByDescending(x=>x.TrainingCatalog!.TrainingName):q.OrderBy(x=>x.TrainingCatalog!.TrainingName),"effectivestartdate"=>d?q.OrderByDescending(x=>x.EffectiveStartDate):q.OrderBy(x=>x.EffectiveStartDate),"isactive"=>d?q.OrderByDescending(x=>x.IsActive):q.OrderBy(x=>x.IsActive),_=>d?q.OrderByDescending(x=>x.Priority).ThenBy(x=>x.RuleName):q.OrderBy(x=>x.Priority).ThenBy(x=>x.RuleName)};}
        private async Task<string> Code(CancellationToken ct){var l=await _db.Set<MstMandatoryTrainingRule>().Where(x=>!x.IsDelete&&x.RuleCode.StartsWith(Prefix)).Select(x=>x.RuleCode).ToListAsync(ct);var u=l.Select(x=>x.Replace(Prefix,"")).Where(x=>int.TryParse(x,out _)).Select(int.Parse).ToHashSet();var n=1;while(u.Contains(n))n++;return Prefix+n.ToString("D5");}
        private async Task<Dictionary<Guid,string>> Actors(IEnumerable<Guid>ids,CancellationToken ct){var v=ids.Where(x=>x!=Guid.Empty).Distinct().ToList();return await _db.Users.Where(x=>v.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,x=>x.DisplayName??x.UserName??x.Email??x.UserCode,ct);}private static string? Actor(IReadOnlyDictionary<Guid,string>a,Guid id)=>id==Guid.Empty?null:a.GetValueOrDefault(id);private Guid Uid(){var s=User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("user_id");return Guid.TryParse(s,out var id)?id:Guid.Empty;}private static Guid? G(Guid?g)=>g is null||g==Guid.Empty?null:g;private static string? T(string?s)=>string.IsNullOrWhiteSpace(s)?null:s.Trim();private static void Page(ref int p,ref int s){p=Math.Max(p,1);s=s<1?25:Math.Min(s,100);}private static List<MandatoryTrainingRuleStringOptionResponse>Periods()=>new(){new(){Value="today",Label="Hari ini"},new(){Value="last7days",Label="7 hari terakhir"},new(){Value="thismonth",Label="Bulan ini"},new(){Value="lastmonth",Label="Bulan lalu"}};
        private static IQueryable<MstMandatoryTrainingRule>Date(IQueryable<MstMandatoryTrainingRule>q,DateTime?s,DateTime?e,string?p){var r=Range(s,e,p);if(r.Item1.HasValue)q=q.Where(x=>x.CreateDateTime>=r.Item1.Value);if(r.Item2.HasValue)q=q.Where(x=>x.CreateDateTime<r.Item2.Value);return q;}private static(DateTime?,DateTime?)Range(DateTime?s,DateTime?e,string?p){if(s.HasValue||e.HasValue)return(s?.Date,e?.Date.AddDays(1));var t=DateTime.UtcNow.Date;return p?.ToLowerInvariant()switch{"today"=>(t,t.AddDays(1)),"last7days"=>(t.AddDays(-6),t.AddDays(1)),"thismonth"=>(new DateTime(t.Year,t.Month,1),new DateTime(t.Year,t.Month,1).AddMonths(1)),"lastmonth"=>(new DateTime(t.Year,t.Month,1).AddMonths(-1),new DateTime(t.Year,t.Month,1)),_=>(null,null)};}
    }
}
