using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuilvianSystemBackend.Areas.Corporate.HumanResource.MasterData.CompetencyAndCredential.DTOs;
using QuilvianSystemBackend.Areas.Corporate.HumanResource.MasterData.CompetencyAndCredential.Models;
using QuilvianSystemBackend.Attributes;
using QuilvianSystemBackend.Constants;
using QuilvianSystemBackend.Repositories;
using QuilvianSystemBackend.Responses;
using QuilvianSystemBackend.Services.Logging;
using System.Security.Claims;

using QuilvianSystemBackend.Areas.Corporate.HumanResource.CredentialingManagement.Models;
using QuilvianSystemBackend.Areas.Corporate.HumanResource.LearningAndDevelopment.Models;
using TrainingCatalogPagedResult = QuilvianSystemBackend.Responses.PagedResult<QuilvianSystemBackend.Areas.Corporate.HumanResource.MasterData.CompetencyAndCredential.DTOs.TrainingCatalogResponse>;

namespace QuilvianSystemBackend.Areas.Corporate.HumanResource.MasterData.CompetencyAndCredential.Controllers
{
    [ApiController,Authorize]
    [Route("api/v1/corporate/human-resource/master-data/training-catalogs")]
    [AccessController("HUMAN_RESOURCE_MASTER_DATA","Human Resource Master Data","Training Catalog",AreaName="Corporate",ControllerName="TrainingCatalog",Description="Corporate human resource master data training catalog",SortOrder=22)]
    [Tags("Corporate / Human Resource / Master Data / Training Catalog")]
    public class TrainingCatalogController:ControllerBase
    {
        private const string Prefix="TRN-RSMMC-"; private const string LogCategory="Corporate.HumanResource.MasterData";
        private static readonly string[] Types={"Internal","External","Orientation","Compliance","Clinical","Technical","Leadership"};
        private static readonly string[] Methods={"Classroom","Online","Hybrid","OnTheJob","Simulation","Workshop","Seminar"};
        private readonly ApplicationDbContext _db; private readonly LoggerService _log; public TrainingCatalogController(ApplicationDbContext db,LoggerService log){_db=db;_log=log;}
        [HttpGet("filters/metadata"),AccessAction("Read","Read Training Catalog",Description="Melihat metadata filter training catalog",AccessType=AccessTypes.Read,SortOrder=1),AccessPermission("TrainingCatalog","Read")]
        public IActionResult Metadata()=>Ok(ApiResponse<TrainingCatalogFilterMetadataResponse>.Ok(new(){DefaultFilter=new(),CustomPeriods=Periods(),TrainingTypeOptions=Types.Select(x=>new TrainingCatalogStringOptionResponse{Value=x,Label=x}).ToList(),DeliveryMethodOptions=Methods.Select(x=>new TrainingCatalogStringOptionResponse{Value=x,Label=x}).ToList(),SortDirections=new(){"asc","desc"},PageSizeOptions=new(){10,25,50,100},SortOptions=new(){new(){Value="createDateTime",Label="Tanggal dibuat"},new(){Value="trainingCode",Label="Kode pelatihan"},new(){Value="trainingName",Label="Nama pelatihan"},new(){Value="categoryName",Label="Kategori"},new(){Value="durationHours",Label="Durasi"},new(){Value="isActive",Label="Status aktif"}}},"Metadata filter training catalog berhasil diambil."));
        [HttpGet("summary"),AccessAction("Read","Read Training Catalog",Description="Melihat ringkasan training catalog",AccessType=AccessTypes.Read,SortOrder=1),AccessPermission("TrainingCatalog","Read")]
        public async Task<IActionResult> Summary(CancellationToken ct){var q=Base();return Ok(ApiResponse<TrainingCatalogSummaryResponse>.Ok(new(){TotalTrainingCatalog=await q.CountAsync(ct),ActiveTrainingCatalog=await q.CountAsync(x=>x.IsActive,ct),InactiveTrainingCatalog=await q.CountAsync(x=>!x.IsActive,ct),MandatoryTrainingCatalog=await q.CountAsync(x=>x.IsMandatory,ct),AssessmentRequiredCatalog=await q.CountAsync(x=>x.RequiresAssessment,ct),CertificateIssuingCatalog=await q.CountAsync(x=>x.IssuesCertificate,ct),ExternalTrainingCatalog=await q.CountAsync(x=>x.TrainingType=="External",ct)},"Ringkasan training catalog berhasil diambil."));}
        [HttpGet,AccessAction("Read","Read Training Catalog",Description="Melihat data training catalog",AccessType=AccessTypes.Read,SortOrder=1),AccessPermission("TrainingCatalog","Read")]
        public async Task<IActionResult> Get([FromQuery]DateTime? startDate,[FromQuery]DateTime? endDate,[FromQuery]string? customPeriod,[FromQuery]Guid? trainingCategoryId,[FromQuery]Guid? certificationTypeId,[FromQuery]string? trainingType,[FromQuery]string? deliveryMethod,[FromQuery]bool? isMandatory,[FromQuery]bool? requiresAssessment,[FromQuery]bool? issuesCertificate,[FromQuery]bool? isActive,[FromQuery]string? search,[FromQuery]string? sortBy="trainingName",[FromQuery]string? sortDirection="asc",[FromQuery]int pageNumber=1,[FromQuery]int pageSize=25,CancellationToken ct=default){NormPage(ref pageNumber,ref pageSize);var q=Filter(Date(Base(),startDate,endDate,customPeriod),trainingCategoryId,certificationTypeId,trainingType,deliveryMethod,isMandatory,requiresAssessment,issuesCertificate,isActive,search);var total=await q.CountAsync(ct);var list=await Sort(q,sortBy,sortDirection).Skip((pageNumber-1)*pageSize).Take(pageSize).ToListAsync(ct);var act=await Actors(list.Select(x=>x.CreateBy),ct);return Ok(ApiResponse<TrainingCatalogPagedResult>.Ok(new(){PageNumber=pageNumber,PageSize=pageSize,TotalData=total,TotalPage=(int)Math.Ceiling(total/(double)pageSize),Items=list.Select(x=>Map(x,act)).ToList()},"Data training catalog berhasil diambil."));}
        [HttpGet("options"),AccessAction("Read","Read Training Catalog",Description="Melihat pilihan training catalog",AccessType=AccessTypes.Read,SortOrder=1),AccessPermission("TrainingCatalog","Read")]
        public async Task<IActionResult> Options([FromQuery]Guid? trainingCategoryId,[FromQuery]string? trainingType,[FromQuery]bool? isMandatory,[FromQuery]bool onlyActive=true,[FromQuery]string? search=null,[FromQuery]int pageNumber=1,[FromQuery]int pageSize=25,CancellationToken ct=default){NormPage(ref pageNumber,ref pageSize);var q=Filter(Base(),trainingCategoryId,null,trainingType,null,isMandatory,null,null,onlyActive?true:null,search);var total=await q.CountAsync(ct);var items=await q.OrderBy(x=>x.TrainingName).Skip((pageNumber-1)*pageSize).Take(pageSize).Select(x=>new TrainingCatalogOptionResponse{Id=x.Id,TrainingCategoryId=x.TrainingCategoryId,TrainingCategoryName=x.TrainingCategory!=null?x.TrainingCategory.TrainingCategoryName:string.Empty,TrainingCode=x.TrainingCode,TrainingName=x.TrainingName,TrainingType=x.TrainingType,DeliveryMethod=x.DeliveryMethod,DurationHours=x.DurationHours,ValidityMonths=x.ValidityMonths,IsMandatory=x.IsMandatory,RequiresAssessment=x.RequiresAssessment,MinimumPassingScore=x.MinimumPassingScore,IssuesCertificate=x.IssuesCertificate}).ToListAsync(ct);return Ok(ApiResponse<TrainingCatalogOptionPagedResponse>.Ok(new(){PageNumber=pageNumber,PageSize=pageSize,TotalData=total,TotalPage=(int)Math.Ceiling(total/(double)pageSize),Items=items},"Pilihan training catalog berhasil diambil."));}
        [HttpGet("{id:guid}"),AccessAction("Read","Read Training Catalog",Description="Melihat detail training catalog",AccessType=AccessTypes.Read,SortOrder=1),AccessPermission("TrainingCatalog","Read")]
        public async Task<IActionResult> Detail(Guid id,CancellationToken ct){var x=await Base().FirstOrDefaultAsync(x=>x.Id==id,ct);if(x==null)return NotFound(ApiResponse<object>.Fail(404,"Training catalog tidak ditemukan."));var a=await Actors(new[]{x.CreateBy,x.UpdateBy},ct);var b=Map(x,a);var r=new TrainingCatalogDetailResponse();Copy(b,r);r.UpdateDateTime=x.UpdateDateTime;r.UpdateBy=x.UpdateBy==Guid.Empty?null:x.UpdateBy;r.UpdateByName=Actor(a,x.UpdateBy);return Ok(ApiResponse<TrainingCatalogDetailResponse>.Ok(r,"Detail training catalog berhasil diambil."));}
        [HttpPost,AccessAction("Create","Create Training Catalog",Description="Membuat training catalog",AccessType=AccessTypes.Create,SortOrder=2),AccessPermission("TrainingCatalog","Create")]
        public async Task<IActionResult> Create([FromBody]CreateTrainingCatalogRequest r,CancellationToken ct){var v=await Validate(null,r,ct);if(!v.ok)return BadRequest(ApiResponse<object>.Fail(400,v.error!));var e=new MstTrainingCatalog{Id=Guid.NewGuid(),TrainingCategoryId=r.TrainingCategoryId,CertificationTypeId=GuidVal(r.CertificationTypeId),TrainingCode=await Code(ct),TrainingName=r.TrainingName.Trim(),TrainingType=Canon(r.TrainingType,Types),DeliveryMethod=Canon(r.DeliveryMethod,Methods),DefaultProviderName=Text(r.DefaultProviderName),DurationHours=r.DurationHours,ValidityMonths=r.ValidityMonths,IsMandatory=r.IsMandatory,RequiresAssessment=r.RequiresAssessment,MinimumPassingScore=r.RequiresAssessment?r.MinimumPassingScore:null,IssuesCertificate=r.IssuesCertificate,Description=Text(r.Description),IsActive=true,CreateDateTime=DateTime.UtcNow,CreateBy=Uid(),IsDelete=false,IsCancel=false};_db.Set<MstTrainingCatalog>().Add(e);await _db.SaveChangesAsync(ct);await _log.InfoAsync(LogCategory,"TrainingCatalog.Create","Membuat training catalog.",new{e.Id,e.TrainingCode,e.TrainingName});return Ok(ApiResponse<TrainingCatalogCreateResponse>.Ok(new(){Id=e.Id,TrainingCode=e.TrainingCode,TrainingName=e.TrainingName,IsActive=e.IsActive},"Training catalog berhasil dibuat."));}
        [HttpPut("{id:guid}"),AccessAction("Update","Update Training Catalog",Description="Mengubah training catalog",AccessType=AccessTypes.Update,SortOrder=3),AccessPermission("TrainingCatalog","Update")]
        public async Task<IActionResult> Update(Guid id,[FromBody]UpdateTrainingCatalogRequest r,CancellationToken ct){var e=await Find(id,ct);if(e==null)return NotFound(ApiResponse<object>.Fail(404,"Training catalog tidak ditemukan."));var v=await Validate(id,r,ct);if(!v.ok)return BadRequest(ApiResponse<object>.Fail(400,v.error!));e.TrainingCategoryId=r.TrainingCategoryId;e.CertificationTypeId=GuidVal(r.CertificationTypeId);e.TrainingName=r.TrainingName.Trim();e.TrainingType=Canon(r.TrainingType,Types);e.DeliveryMethod=Canon(r.DeliveryMethod,Methods);e.DefaultProviderName=Text(r.DefaultProviderName);e.DurationHours=r.DurationHours;e.ValidityMonths=r.ValidityMonths;e.IsMandatory=r.IsMandatory;e.RequiresAssessment=r.RequiresAssessment;e.MinimumPassingScore=r.RequiresAssessment?r.MinimumPassingScore:null;e.IssuesCertificate=r.IssuesCertificate;e.Description=Text(r.Description);e.IsActive=r.IsActive;e.UpdateDateTime=DateTime.UtcNow;e.UpdateBy=Uid();await _db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.Ok(null,"Training catalog berhasil diperbarui."));}
        [HttpPatch("{id:guid}/status"),AccessAction("Update","Update Training Catalog Status",Description="Mengubah status training catalog",AccessType=AccessTypes.Update,SortOrder=4),AccessPermission("TrainingCatalog","Update")]
        public async Task<IActionResult> Status(Guid id,[FromBody]UpdateTrainingCatalogStatusRequest r,CancellationToken ct){var e=await Find(id,ct);if(e==null)return NotFound(ApiResponse<object>.Fail(404,"Training catalog tidak ditemukan."));e.IsActive=r.IsActive;e.UpdateDateTime=DateTime.UtcNow;e.UpdateBy=Uid();await _db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.Ok(null,"Status training catalog berhasil diperbarui."));}
        [HttpDelete("{id:guid}"),AccessAction("Delete","Delete Training Catalog",Description="Menghapus training catalog",AccessType=AccessTypes.Delete,SortOrder=5),AccessPermission("TrainingCatalog","Delete")]
        public async Task<IActionResult> Delete(Guid id,CancellationToken ct){var e=await Find(id,ct);if(e==null)return NotFound(ApiResponse<object>.Fail(404,"Training catalog tidak ditemukan."));var used=await _db.Set<MstMandatoryTrainingRule>().AnyAsync(x=>x.TrainingCatalogId==id&&!x.IsDelete,ct)||await _db.Set<WfpTrainingRecord>().AnyAsync(x=>x.TrainingCatalogId==id&&!x.IsDelete,ct)||await _db.Set<MstCredentialingRequirement>().AnyAsync(x=>x.TrainingCatalogId==id&&!x.IsDelete,ct);if(used)return BadRequest(ApiResponse<object>.Fail(400,"Training catalog tidak dapat dihapus karena sudah digunakan."));SoftDelete(e);await _db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.Ok(null,"Training catalog berhasil dihapus."));}
        private IQueryable<MstTrainingCatalog> Base()=>_db.Set<MstTrainingCatalog>().AsNoTracking().Include(x=>x.TrainingCategory).Include(x=>x.CertificationType).Where(x=>!x.IsDelete);
        private async Task<MstTrainingCatalog?> Find(Guid id,CancellationToken ct)=>await _db.Set<MstTrainingCatalog>().FirstOrDefaultAsync(x=>x.Id==id&&!x.IsDelete,ct);
        private async Task<(bool ok,string? error)> Validate(Guid? id,CreateTrainingCatalogRequest r,CancellationToken ct){if(r.TrainingCategoryId==Guid.Empty)return(false,"Training category wajib dipilih.");if(!await _db.Set<MstTrainingCategory>().AnyAsync(x=>x.Id==r.TrainingCategoryId&&x.IsActive&&!x.IsDelete,ct))return(false,"Training category tidak ditemukan atau tidak aktif.");if(r.CertificationTypeId.HasValue&&!await _db.Set<MstCertificationType>().AnyAsync(x=>x.Id==r.CertificationTypeId&&x.IsActive&&!x.IsDelete,ct))return(false,"Certification type tidak ditemukan atau tidak aktif.");if(string.IsNullOrWhiteSpace(r.TrainingName))return(false,"Nama pelatihan wajib diisi.");if(!Types.Any(x=>x.Equals(r.TrainingType,StringComparison.OrdinalIgnoreCase)))return(false,"Training type tidak valid.");if(!Methods.Any(x=>x.Equals(r.DeliveryMethod,StringComparison.OrdinalIgnoreCase)))return(false,"Delivery method tidak valid.");if(r.DurationHours<0)return(false,"Durasi tidak boleh negatif.");if(r.ValidityMonths.HasValue&&r.ValidityMonths<=0)return(false,"Validity months harus lebih dari 0.");if(r.RequiresAssessment&&!r.MinimumPassingScore.HasValue)return(false,"Minimum passing score wajib ketika assessment diperlukan.");if(r.MinimumPassingScore is <0 or >100)return(false,"Minimum passing score harus antara 0 dan 100.");var name=r.TrainingName.Trim().ToLower();var q=_db.Set<MstTrainingCatalog>().AsNoTracking().Where(x=>!x.IsDelete&&x.TrainingCategoryId==r.TrainingCategoryId&&x.TrainingName.ToLower()==name);if(id.HasValue)q=q.Where(x=>x.Id!=id);if(await q.AnyAsync(ct))return(false,"Nama pelatihan pada kategori tersebut sudah digunakan.");return(true,null);}
        private TrainingCatalogResponse Map(MstTrainingCatalog x,IReadOnlyDictionary<Guid,string>a)=>new(){Id=x.Id,TrainingCategoryId=x.TrainingCategoryId,TrainingCategoryCode=x.TrainingCategory?.TrainingCategoryCode??string.Empty,TrainingCategoryName=x.TrainingCategory?.TrainingCategoryName??string.Empty,CertificationTypeId=x.CertificationTypeId,CertificationTypeCode=x.CertificationType?.CertificationTypeCode,CertificationTypeName=x.CertificationType?.CertificationTypeName,TrainingCode=x.TrainingCode,TrainingName=x.TrainingName,TrainingType=x.TrainingType,DeliveryMethod=x.DeliveryMethod,DefaultProviderName=x.DefaultProviderName,DurationHours=x.DurationHours,ValidityMonths=x.ValidityMonths,IsMandatory=x.IsMandatory,RequiresAssessment=x.RequiresAssessment,MinimumPassingScore=x.MinimumPassingScore,IssuesCertificate=x.IssuesCertificate,Description=x.Description,IsActive=x.IsActive,MandatoryTrainingRuleCount=_db.Set<MstMandatoryTrainingRule>().Count(r=>r.TrainingCatalogId==x.Id&&!r.IsDelete),WorkforceTrainingRecordCount=_db.Set<WfpTrainingRecord>().Count(r=>r.TrainingCatalogId==x.Id&&!r.IsDelete),CredentialingRequirementCount=_db.Set<MstCredentialingRequirement>().Count(r=>r.TrainingCatalogId==x.Id&&!r.IsDelete),CreateDateTime=x.CreateDateTime,CreateBy=x.CreateBy==Guid.Empty?null:x.CreateBy,CreateByName=Actor(a,x.CreateBy)};
        private static void Copy(TrainingCatalogResponse b,TrainingCatalogDetailResponse r){foreach(var p in typeof(TrainingCatalogResponse).GetProperties())p.SetValue(r,p.GetValue(b));}
        private IQueryable<MstTrainingCatalog> Filter(IQueryable<MstTrainingCatalog> q,Guid? c,Guid? cert,string? type,string? method,bool? mandatory,bool? assess,bool? issue,bool? active,string? search){if(c.HasValue)q=q.Where(x=>x.TrainingCategoryId==c);if(cert.HasValue)q=q.Where(x=>x.CertificationTypeId==cert);if(!string.IsNullOrWhiteSpace(type))q=q.Where(x=>x.TrainingType==Canon(type,Types));if(!string.IsNullOrWhiteSpace(method))q=q.Where(x=>x.DeliveryMethod==Canon(method,Methods));if(mandatory.HasValue)q=q.Where(x=>x.IsMandatory==mandatory);if(assess.HasValue)q=q.Where(x=>x.RequiresAssessment==assess);if(issue.HasValue)q=q.Where(x=>x.IssuesCertificate==issue);if(active.HasValue)q=q.Where(x=>x.IsActive==active);if(!string.IsNullOrWhiteSpace(search)){var k=search.Trim().ToLower();q=q.Where(x=>x.TrainingCode.ToLower().Contains(k)||x.TrainingName.ToLower().Contains(k)||(x.DefaultProviderName!=null&&x.DefaultProviderName.ToLower().Contains(k))||(x.TrainingCategory!=null&&x.TrainingCategory.TrainingCategoryName.ToLower().Contains(k)));}return q;}
        private static IOrderedQueryable<MstTrainingCatalog> Sort(IQueryable<MstTrainingCatalog>q,string? b,string? d){var desc=string.Equals(d,"desc",StringComparison.OrdinalIgnoreCase);return(b??"trainingName").ToLowerInvariant() switch{"createdatetime"=>desc?q.OrderByDescending(x=>x.CreateDateTime):q.OrderBy(x=>x.CreateDateTime),"trainingcode"=>desc?q.OrderByDescending(x=>x.TrainingCode):q.OrderBy(x=>x.TrainingCode),"categoryname"=>desc?q.OrderByDescending(x=>x.TrainingCategory!.TrainingCategoryName):q.OrderBy(x=>x.TrainingCategory!.TrainingCategoryName),"durationhours"=>desc?q.OrderByDescending(x=>x.DurationHours):q.OrderBy(x=>x.DurationHours),"isactive"=>desc?q.OrderByDescending(x=>x.IsActive):q.OrderBy(x=>x.IsActive),_=>desc?q.OrderByDescending(x=>x.TrainingName):q.OrderBy(x=>x.TrainingName)};}
        private async Task<string> Code(CancellationToken ct){var l=await _db.Set<MstTrainingCatalog>().Where(x=>!x.IsDelete&&x.TrainingCode.StartsWith(Prefix)).Select(x=>x.TrainingCode).ToListAsync(ct);var u=l.Select(x=>x.Replace(Prefix,"")).Where(x=>int.TryParse(x,out _)).Select(int.Parse).ToHashSet();var n=1;while(u.Contains(n))n++;return Prefix+n.ToString("D5");}
        private void SoftDelete(MstTrainingCatalog e){var n=DateTime.UtcNow;var a=Uid();e.IsDelete=true;e.IsActive=false;e.DeleteDateTime=n;e.DeleteBy=a;e.UpdateDateTime=n;e.UpdateBy=a;} private Guid Uid(){var s=User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("user_id");return Guid.TryParse(s,out var id)?id:Guid.Empty;} private static string? Text(string? s)=>string.IsNullOrWhiteSpace(s)?null:s.Trim();private static Guid? GuidVal(Guid? g)=>g is null||g==Guid.Empty?null:g;private static string Canon(string v,IEnumerable<string> a)=>a.First(x=>x.Equals(v.Trim(),StringComparison.OrdinalIgnoreCase));
        private async Task<Dictionary<Guid,string>> Actors(IEnumerable<Guid> ids,CancellationToken ct){var v=ids.Where(x=>x!=Guid.Empty).Distinct().ToList();return await _db.Users.Where(x=>v.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,x=>x.DisplayName??x.UserName??x.Email??x.UserCode,ct);}private static string? Actor(IReadOnlyDictionary<Guid,string>a,Guid id)=>id==Guid.Empty?null:a.GetValueOrDefault(id);private static void NormPage(ref int p,ref int s){p=Math.Max(p,1);s=s<1?25:Math.Min(s,100);}private static List<TrainingCatalogStringOptionResponse> Periods()=>new(){new(){Value="today",Label="Hari ini"},new(){Value="last7days",Label="7 hari terakhir"},new(){Value="thismonth",Label="Bulan ini"},new(){Value="lastmonth",Label="Bulan lalu"}};
        private static IQueryable<MstTrainingCatalog>Date(IQueryable<MstTrainingCatalog>q,DateTime?s,DateTime?e,string?p){var r=Range(s,e,p);if(r.Item1.HasValue)q=q.Where(x=>x.CreateDateTime>=r.Item1.Value);if(r.Item2.HasValue)q=q.Where(x=>x.CreateDateTime<r.Item2.Value);return q;}private static(DateTime?,DateTime?)Range(DateTime?s,DateTime?e,string?p){if(s.HasValue||e.HasValue)return(s?.Date,e?.Date.AddDays(1));var t=DateTime.UtcNow.Date;return p?.ToLowerInvariant()switch{"today"=>(t,t.AddDays(1)),"last7days"=>(t.AddDays(-6),t.AddDays(1)),"thismonth"=>(new DateTime(t.Year,t.Month,1),new DateTime(t.Year,t.Month,1).AddMonths(1)),"lastmonth"=>(new DateTime(t.Year,t.Month,1).AddMonths(-1),new DateTime(t.Year,t.Month,1)),_=>(null,null)};}
    }
}
