// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using QuilvianSystemBackend.Repositories;

#nullable disable

namespace QuilvianSystemBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909075500_RenameTrxPatientEncounterGuarantorToRegPrefix")]
    partial class RenameTrxPatientEncounterGuarantorToRegPrefix
    {
    }
}